// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mup/v1/mup.proto

package mupv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Ytaihei/free5gc-srv6-mup-lab/api/mup/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ObserverIngestServiceName is the fully-qualified name of the ObserverIngestService service.
	ObserverIngestServiceName = "mup.v1.ObserverIngestService"
	// ControllerServiceName is the fully-qualified name of the ControllerService service.
	ControllerServiceName = "mup.v1.ControllerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ObserverIngestServiceSyncSnapshotProcedure is the fully-qualified name of the
	// ObserverIngestService's SyncSnapshot RPC.
	ObserverIngestServiceSyncSnapshotProcedure = "/mup.v1.ObserverIngestService/SyncSnapshot"
	// ControllerServiceStatusProcedure is the fully-qualified name of the ControllerService's Status
	// RPC.
	ControllerServiceStatusProcedure = "/mup.v1.ControllerService/Status"
	// ControllerServiceListSessionsProcedure is the fully-qualified name of the ControllerService's
	// ListSessions RPC.
	ControllerServiceListSessionsProcedure = "/mup.v1.ControllerService/ListSessions"
	// ControllerServiceSetSuppressionProcedure is the fully-qualified name of the ControllerService's
	// SetSuppression RPC.
	ControllerServiceSetSuppressionProcedure = "/mup.v1.ControllerService/SetSuppression"
	// ControllerServiceReconcileProcedure is the fully-qualified name of the ControllerService's
	// Reconcile RPC.
	ControllerServiceReconcileProcedure = "/mup.v1.ControllerService/Reconcile"
)

// ObserverIngestServiceClient is a client for the mup.v1.ObserverIngestService service.
type ObserverIngestServiceClient interface {
	SyncSnapshot(context.Context, *connect.Request[v1.SyncSnapshotRequest]) (*connect.Response[v1.SyncSnapshotResponse], error)
}

// NewObserverIngestServiceClient constructs a client for the mup.v1.ObserverIngestService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewObserverIngestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ObserverIngestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	observerIngestServiceMethods := v1.File_mup_v1_mup_proto.Services().ByName("ObserverIngestService").Methods()
	return &observerIngestServiceClient{
		syncSnapshot: connect.NewClient[v1.SyncSnapshotRequest, v1.SyncSnapshotResponse](
			httpClient,
			baseURL+ObserverIngestServiceSyncSnapshotProcedure,
			connect.WithSchema(observerIngestServiceMethods.ByName("SyncSnapshot")),
			connect.WithClientOptions(opts...),
		),
	}
}

// observerIngestServiceClient implements ObserverIngestServiceClient.
type observerIngestServiceClient struct {
	syncSnapshot *connect.Client[v1.SyncSnapshotRequest, v1.SyncSnapshotResponse]
}

// SyncSnapshot calls mup.v1.ObserverIngestService.SyncSnapshot.
func (c *observerIngestServiceClient) SyncSnapshot(ctx context.Context, req *connect.Request[v1.SyncSnapshotRequest]) (*connect.Response[v1.SyncSnapshotResponse], error) {
	return c.syncSnapshot.CallUnary(ctx, req)
}

// ObserverIngestServiceHandler is an implementation of the mup.v1.ObserverIngestService service.
type ObserverIngestServiceHandler interface {
	SyncSnapshot(context.Context, *connect.Request[v1.SyncSnapshotRequest]) (*connect.Response[v1.SyncSnapshotResponse], error)
}

// NewObserverIngestServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewObserverIngestServiceHandler(svc ObserverIngestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	observerIngestServiceMethods := v1.File_mup_v1_mup_proto.Services().ByName("ObserverIngestService").Methods()
	observerIngestServiceSyncSnapshotHandler := connect.NewUnaryHandler(
		ObserverIngestServiceSyncSnapshotProcedure,
		svc.SyncSnapshot,
		connect.WithSchema(observerIngestServiceMethods.ByName("SyncSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mup.v1.ObserverIngestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ObserverIngestServiceSyncSnapshotProcedure:
			observerIngestServiceSyncSnapshotHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedObserverIngestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedObserverIngestServiceHandler struct{}

func (UnimplementedObserverIngestServiceHandler) SyncSnapshot(context.Context, *connect.Request[v1.SyncSnapshotRequest]) (*connect.Response[v1.SyncSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mup.v1.ObserverIngestService.SyncSnapshot is not implemented"))
}

// ControllerServiceClient is a client for the mup.v1.ControllerService service.
type ControllerServiceClient interface {
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	SetSuppression(context.Context, *connect.Request[v1.SetSuppressionRequest]) (*connect.Response[v1.SetSuppressionResponse], error)
	Reconcile(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.ReconcileResponse], error)
}

// NewControllerServiceClient constructs a client for the mup.v1.ControllerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewControllerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ControllerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	controllerServiceMethods := v1.File_mup_v1_mup_proto.Services().ByName("ControllerService").Methods()
	return &controllerServiceClient{
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+ControllerServiceStatusProcedure,
			connect.WithSchema(controllerServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+ControllerServiceListSessionsProcedure,
			connect.WithSchema(controllerServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		setSuppression: connect.NewClient[v1.SetSuppressionRequest, v1.SetSuppressionResponse](
			httpClient,
			baseURL+ControllerServiceSetSuppressionProcedure,
			connect.WithSchema(controllerServiceMethods.ByName("SetSuppression")),
			connect.WithClientOptions(opts...),
		),
		reconcile: connect.NewClient[emptypb.Empty, v1.ReconcileResponse](
			httpClient,
			baseURL+ControllerServiceReconcileProcedure,
			connect.WithSchema(controllerServiceMethods.ByName("Reconcile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// controllerServiceClient implements ControllerServiceClient.
type controllerServiceClient struct {
	status         *connect.Client[v1.StatusRequest, v1.StatusResponse]
	listSessions   *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	setSuppression *connect.Client[v1.SetSuppressionRequest, v1.SetSuppressionResponse]
	reconcile      *connect.Client[emptypb.Empty, v1.ReconcileResponse]
}

// Status calls mup.v1.ControllerService.Status.
func (c *controllerServiceClient) Status(ctx context.Context, req *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// ListSessions calls mup.v1.ControllerService.ListSessions.
func (c *controllerServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// SetSuppression calls mup.v1.ControllerService.SetSuppression.
func (c *controllerServiceClient) SetSuppression(ctx context.Context, req *connect.Request[v1.SetSuppressionRequest]) (*connect.Response[v1.SetSuppressionResponse], error) {
	return c.setSuppression.CallUnary(ctx, req)
}

// Reconcile calls mup.v1.ControllerService.Reconcile.
func (c *controllerServiceClient) Reconcile(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.ReconcileResponse], error) {
	return c.reconcile.CallUnary(ctx, req)
}

// ControllerServiceHandler is an implementation of the mup.v1.ControllerService service.
type ControllerServiceHandler interface {
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	SetSuppression(context.Context, *connect.Request[v1.SetSuppressionRequest]) (*connect.Response[v1.SetSuppressionResponse], error)
	Reconcile(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.ReconcileResponse], error)
}

// NewControllerServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewControllerServiceHandler(svc ControllerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	controllerServiceMethods := v1.File_mup_v1_mup_proto.Services().ByName("ControllerService").Methods()
	controllerServiceStatusHandler := connect.NewUnaryHandler(
		ControllerServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(controllerServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	controllerServiceListSessionsHandler := connect.NewUnaryHandler(
		ControllerServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(controllerServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	controllerServiceSetSuppressionHandler := connect.NewUnaryHandler(
		ControllerServiceSetSuppressionProcedure,
		svc.SetSuppression,
		connect.WithSchema(controllerServiceMethods.ByName("SetSuppression")),
		connect.WithHandlerOptions(opts...),
	)
	controllerServiceReconcileHandler := connect.NewUnaryHandler(
		ControllerServiceReconcileProcedure,
		svc.Reconcile,
		connect.WithSchema(controllerServiceMethods.ByName("Reconcile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mup.v1.ControllerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ControllerServiceStatusProcedure:
			controllerServiceStatusHandler.ServeHTTP(w, r)
		case ControllerServiceListSessionsProcedure:
			controllerServiceListSessionsHandler.ServeHTTP(w, r)
		case ControllerServiceSetSuppressionProcedure:
			controllerServiceSetSuppressionHandler.ServeHTTP(w, r)
		case ControllerServiceReconcileProcedure:
			controllerServiceReconcileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedControllerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedControllerServiceHandler struct{}

func (UnimplementedControllerServiceHandler) Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mup.v1.ControllerService.Status is not implemented"))
}

func (UnimplementedControllerServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mup.v1.ControllerService.ListSessions is not implemented"))
}

func (UnimplementedControllerServiceHandler) SetSuppression(context.Context, *connect.Request[v1.SetSuppressionRequest]) (*connect.Response[v1.SetSuppressionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mup.v1.ControllerService.SetSuppression is not implemented"))
}

func (UnimplementedControllerServiceHandler) Reconcile(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.ReconcileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mup.v1.ControllerService.Reconcile is not implemented"))
}
