// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mup/v1/mup.proto

package mupv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PFCP-derived state. The observer publishes only sessions whose PFCP
// transaction completed with an accepted response.
type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CpSeid           uint64                 `protobuf:"varint,2,opt,name=cp_seid,json=cpSeid,proto3" json:"cp_seid,omitempty"`
	UpSeid           uint64                 `protobuf:"varint,3,opt,name=up_seid,json=upSeid,proto3" json:"up_seid,omitempty"`
	UeIpv4           string                 `protobuf:"bytes,4,opt,name=ue_ipv4,json=ueIpv4,proto3" json:"ue_ipv4,omitempty"`
	Dnn              string                 `protobuf:"bytes,5,opt,name=dnn,proto3" json:"dnn,omitempty"`
	Supi             string                 `protobuf:"bytes,6,opt,name=supi,proto3" json:"supi,omitempty"`
	UpfGtpIpv4       string                 `protobuf:"bytes,7,opt,name=upf_gtp_ipv4,json=upfGtpIpv4,proto3" json:"upf_gtp_ipv4,omitempty"`
	UplinkTeid       uint32                 `protobuf:"varint,8,opt,name=uplink_teid,json=uplinkTeid,proto3" json:"uplink_teid,omitempty"`
	RanGtpIpv4       string                 `protobuf:"bytes,9,opt,name=ran_gtp_ipv4,json=ranGtpIpv4,proto3" json:"ran_gtp_ipv4,omitempty"`
	DownlinkTeid     uint32                 `protobuf:"varint,10,opt,name=downlink_teid,json=downlinkTeid,proto3" json:"downlink_teid,omitempty"`
	Qfi              uint32                 `protobuf:"varint,11,opt,name=qfi,proto3" json:"qfi,omitempty"`
	ObservedUnixNano int64                  `protobuf:"varint,12,opt,name=observed_unix_nano,json=observedUnixNano,proto3" json:"observed_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_mup_v1_mup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Session) GetCpSeid() uint64 {
	if x != nil {
		return x.CpSeid
	}
	return 0
}

func (x *Session) GetUpSeid() uint64 {
	if x != nil {
		return x.UpSeid
	}
	return 0
}

func (x *Session) GetUeIpv4() string {
	if x != nil {
		return x.UeIpv4
	}
	return ""
}

func (x *Session) GetDnn() string {
	if x != nil {
		return x.Dnn
	}
	return ""
}

func (x *Session) GetSupi() string {
	if x != nil {
		return x.Supi
	}
	return ""
}

func (x *Session) GetUpfGtpIpv4() string {
	if x != nil {
		return x.UpfGtpIpv4
	}
	return ""
}

func (x *Session) GetUplinkTeid() uint32 {
	if x != nil {
		return x.UplinkTeid
	}
	return 0
}

func (x *Session) GetRanGtpIpv4() string {
	if x != nil {
		return x.RanGtpIpv4
	}
	return ""
}

func (x *Session) GetDownlinkTeid() uint32 {
	if x != nil {
		return x.DownlinkTeid
	}
	return 0
}

func (x *Session) GetQfi() uint32 {
	if x != nil {
		return x.Qfi
	}
	return 0
}

func (x *Session) GetObservedUnixNano() int64 {
	if x != nil {
		return x.ObservedUnixNano
	}
	return 0
}

type SyncSnapshotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObserverId       string                 `protobuf:"bytes,1,opt,name=observer_id,json=observerId,proto3" json:"observer_id,omitempty"`
	Generation       uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	ObservedUnixNano int64                  `protobuf:"varint,3,opt,name=observed_unix_nano,json=observedUnixNano,proto3" json:"observed_unix_nano,omitempty"`
	Sessions         []*Session             `protobuf:"bytes,4,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncSnapshotRequest) Reset() {
	*x = SyncSnapshotRequest{}
	mi := &file_mup_v1_mup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSnapshotRequest) ProtoMessage() {}

func (x *SyncSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSnapshotRequest.ProtoReflect.Descriptor instead.
func (*SyncSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{1}
}

func (x *SyncSnapshotRequest) GetObserverId() string {
	if x != nil {
		return x.ObserverId
	}
	return ""
}

func (x *SyncSnapshotRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SyncSnapshotRequest) GetObservedUnixNano() int64 {
	if x != nil {
		return x.ObservedUnixNano
	}
	return 0
}

func (x *SyncSnapshotRequest) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SyncSnapshotResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AcceptedGeneration uint64                 `protobuf:"varint,1,opt,name=accepted_generation,json=acceptedGeneration,proto3" json:"accepted_generation,omitempty"`
	SelectedSessions   uint32                 `protobuf:"varint,2,opt,name=selected_sessions,json=selectedSessions,proto3" json:"selected_sessions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncSnapshotResponse) Reset() {
	*x = SyncSnapshotResponse{}
	mi := &file_mup_v1_mup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSnapshotResponse) ProtoMessage() {}

func (x *SyncSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSnapshotResponse.ProtoReflect.Descriptor instead.
func (*SyncSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{2}
}

func (x *SyncSnapshotResponse) GetAcceptedGeneration() uint64 {
	if x != nil {
		return x.AcceptedGeneration
	}
	return 0
}

func (x *SyncSnapshotResponse) GetSelectedSessions() uint32 {
	if x != nil {
		return x.SelectedSessions
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_mup_v1_mup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ObserverId               string                 `protobuf:"bytes,1,opt,name=observer_id,json=observerId,proto3" json:"observer_id,omitempty"`
	Generation               uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	ObserverLastSeenUnixNano int64                  `protobuf:"varint,3,opt,name=observer_last_seen_unix_nano,json=observerLastSeenUnixNano,proto3" json:"observer_last_seen_unix_nano,omitempty"`
	ObserverLeaseValid       bool                   `protobuf:"varint,4,opt,name=observer_lease_valid,json=observerLeaseValid,proto3" json:"observer_lease_valid,omitempty"`
	ObservedSessions         uint32                 `protobuf:"varint,5,opt,name=observed_sessions,json=observedSessions,proto3" json:"observed_sessions,omitempty"`
	SelectedSessions         uint32                 `protobuf:"varint,6,opt,name=selected_sessions,json=selectedSessions,proto3" json:"selected_sessions,omitempty"`
	AdvertisedRoutes         uint32                 `protobuf:"varint,7,opt,name=advertised_routes,json=advertisedRoutes,proto3" json:"advertised_routes,omitempty"`
	BgpState                 string                 `protobuf:"bytes,8,opt,name=bgp_state,json=bgpState,proto3" json:"bgp_state,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_mup_v1_mup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetObserverId() string {
	if x != nil {
		return x.ObserverId
	}
	return ""
}

func (x *StatusResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *StatusResponse) GetObserverLastSeenUnixNano() int64 {
	if x != nil {
		return x.ObserverLastSeenUnixNano
	}
	return 0
}

func (x *StatusResponse) GetObserverLeaseValid() bool {
	if x != nil {
		return x.ObserverLeaseValid
	}
	return false
}

func (x *StatusResponse) GetObservedSessions() uint32 {
	if x != nil {
		return x.ObservedSessions
	}
	return 0
}

func (x *StatusResponse) GetSelectedSessions() uint32 {
	if x != nil {
		return x.SelectedSessions
	}
	return 0
}

func (x *StatusResponse) GetAdvertisedRoutes() uint32 {
	if x != nil {
		return x.AdvertisedRoutes
	}
	return 0
}

func (x *StatusResponse) GetBgpState() string {
	if x != nil {
		return x.BgpState
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_mup_v1_mup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{5}
}

type ControlledSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Selected      bool                   `protobuf:"varint,2,opt,name=selected,proto3" json:"selected,omitempty"`
	Suppressed    bool                   `protobuf:"varint,3,opt,name=suppressed,proto3" json:"suppressed,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Advertised    bool                   `protobuf:"varint,5,opt,name=advertised,proto3" json:"advertised,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlledSession) Reset() {
	*x = ControlledSession{}
	mi := &file_mup_v1_mup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlledSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlledSession) ProtoMessage() {}

func (x *ControlledSession) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlledSession.ProtoReflect.Descriptor instead.
func (*ControlledSession) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{6}
}

func (x *ControlledSession) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ControlledSession) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *ControlledSession) GetSuppressed() bool {
	if x != nil {
		return x.Suppressed
	}
	return false
}

func (x *ControlledSession) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ControlledSession) GetAdvertised() bool {
	if x != nil {
		return x.Advertised
	}
	return false
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ControlledSession   `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_mup_v1_mup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{7}
}

func (x *ListSessionsResponse) GetSessions() []*ControlledSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SetSuppressionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Suppressed    bool                   `protobuf:"varint,2,opt,name=suppressed,proto3" json:"suppressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSuppressionRequest) Reset() {
	*x = SetSuppressionRequest{}
	mi := &file_mup_v1_mup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSuppressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSuppressionRequest) ProtoMessage() {}

func (x *SetSuppressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSuppressionRequest.ProtoReflect.Descriptor instead.
func (*SetSuppressionRequest) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{8}
}

func (x *SetSuppressionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSuppressionRequest) GetSuppressed() bool {
	if x != nil {
		return x.Suppressed
	}
	return false
}

type SetSuppressionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *ControlledSession     `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSuppressionResponse) Reset() {
	*x = SetSuppressionResponse{}
	mi := &file_mup_v1_mup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSuppressionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSuppressionResponse) ProtoMessage() {}

func (x *SetSuppressionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSuppressionResponse.ProtoReflect.Descriptor instead.
func (*SetSuppressionResponse) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{9}
}

func (x *SetSuppressionResponse) GetSession() *ControlledSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type ReconcileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SelectedSessions uint32                 `protobuf:"varint,1,opt,name=selected_sessions,json=selectedSessions,proto3" json:"selected_sessions,omitempty"`
	AdvertisedRoutes uint32                 `protobuf:"varint,2,opt,name=advertised_routes,json=advertisedRoutes,proto3" json:"advertised_routes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_mup_v1_mup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mup_v1_mup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_mup_v1_mup_proto_rawDescGZIP(), []int{10}
}

func (x *ReconcileResponse) GetSelectedSessions() uint32 {
	if x != nil {
		return x.SelectedSessions
	}
	return 0
}

func (x *ReconcileResponse) GetAdvertisedRoutes() uint32 {
	if x != nil {
		return x.AdvertisedRoutes
	}
	return 0
}

var File_mup_v1_mup_proto protoreflect.FileDescriptor

const file_mup_v1_mup_proto_rawDesc = "" +
	"\n" +
	"\x10mup/v1/mup.proto\x12\x06mup.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xd6\x02\n" +
	"\aSession\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\acp_seid\x18\x02 \x01(\x04R\x06cpSeid\x12\x17\n" +
	"\aup_seid\x18\x03 \x01(\x04R\x06upSeid\x12\x17\n" +
	"\aue_ipv4\x18\x04 \x01(\tR\x06ueIpv4\x12\x10\n" +
	"\x03dnn\x18\x05 \x01(\tR\x03dnn\x12\x12\n" +
	"\x04supi\x18\x06 \x01(\tR\x04supi\x12 \n" +
	"\fupf_gtp_ipv4\x18\a \x01(\tR\n" +
	"upfGtpIpv4\x12\x1f\n" +
	"\vuplink_teid\x18\b \x01(\rR\n" +
	"uplinkTeid\x12 \n" +
	"\fran_gtp_ipv4\x18\t \x01(\tR\n" +
	"ranGtpIpv4\x12#\n" +
	"\rdownlink_teid\x18\n" +
	" \x01(\rR\fdownlinkTeid\x12\x10\n" +
	"\x03qfi\x18\v \x01(\rR\x03qfi\x12,\n" +
	"\x12observed_unix_nano\x18\f \x01(\x03R\x10observedUnixNano\"\xb1\x01\n" +
	"\x13SyncSnapshotRequest\x12\x1f\n" +
	"\vobserver_id\x18\x01 \x01(\tR\n" +
	"observerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12,\n" +
	"\x12observed_unix_nano\x18\x03 \x01(\x03R\x10observedUnixNano\x12+\n" +
	"\bsessions\x18\x04 \x03(\v2\x0f.mup.v1.SessionR\bsessions\"t\n" +
	"\x14SyncSnapshotResponse\x12/\n" +
	"\x13accepted_generation\x18\x01 \x01(\x04R\x12acceptedGeneration\x12+\n" +
	"\x11selected_sessions\x18\x02 \x01(\rR\x10selectedSessions\"\x0f\n" +
	"\rStatusRequest\"\xe7\x02\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vobserver_id\x18\x01 \x01(\tR\n" +
	"observerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12>\n" +
	"\x1cobserver_last_seen_unix_nano\x18\x03 \x01(\x03R\x18observerLastSeenUnixNano\x120\n" +
	"\x14observer_lease_valid\x18\x04 \x01(\bR\x12observerLeaseValid\x12+\n" +
	"\x11observed_sessions\x18\x05 \x01(\rR\x10observedSessions\x12+\n" +
	"\x11selected_sessions\x18\x06 \x01(\rR\x10selectedSessions\x12+\n" +
	"\x11advertised_routes\x18\a \x01(\rR\x10advertisedRoutes\x12\x1b\n" +
	"\tbgp_state\x18\b \x01(\tR\bbgpState\"\x15\n" +
	"\x13ListSessionsRequest\"\xb2\x01\n" +
	"\x11ControlledSession\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.mup.v1.SessionR\asession\x12\x1a\n" +
	"\bselected\x18\x02 \x01(\bR\bselected\x12\x1e\n" +
	"\n" +
	"suppressed\x18\x03 \x01(\bR\n" +
	"suppressed\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"advertised\x18\x05 \x01(\bR\n" +
	"advertised\"M\n" +
	"\x14ListSessionsResponse\x125\n" +
	"\bsessions\x18\x01 \x03(\v2\x19.mup.v1.ControlledSessionR\bsessions\"I\n" +
	"\x15SetSuppressionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"suppressed\x18\x02 \x01(\bR\n" +
	"suppressed\"M\n" +
	"\x16SetSuppressionResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.mup.v1.ControlledSessionR\asession\"m\n" +
	"\x11ReconcileResponse\x12+\n" +
	"\x11selected_sessions\x18\x01 \x01(\rR\x10selectedSessions\x12+\n" +
	"\x11advertised_routes\x18\x02 \x01(\rR\x10advertisedRoutes2b\n" +
	"\x15ObserverIngestService\x12I\n" +
	"\fSyncSnapshot\x12\x1b.mup.v1.SyncSnapshotRequest\x1a\x1c.mup.v1.SyncSnapshotResponse2\xa8\x02\n" +
	"\x11ControllerService\x127\n" +
	"\x06Status\x12\x15.mup.v1.StatusRequest\x1a\x16.mup.v1.StatusResponse\x12I\n" +
	"\fListSessions\x12\x1b.mup.v1.ListSessionsRequest\x1a\x1c.mup.v1.ListSessionsResponse\x12O\n" +
	"\x0eSetSuppression\x12\x1d.mup.v1.SetSuppressionRequest\x1a\x1e.mup.v1.SetSuppressionResponse\x12>\n" +
	"\tReconcile\x12\x16.google.protobuf.Empty\x1a\x19.mup.v1.ReconcileResponseB:Z8github.com/Ytaihei/free5gc-srv6-mup-lab/api/mup/v1;mupv1b\x06proto3"

var (
	file_mup_v1_mup_proto_rawDescOnce sync.Once
	file_mup_v1_mup_proto_rawDescData []byte
)

func file_mup_v1_mup_proto_rawDescGZIP() []byte {
	file_mup_v1_mup_proto_rawDescOnce.Do(func() {
		file_mup_v1_mup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mup_v1_mup_proto_rawDesc), len(file_mup_v1_mup_proto_rawDesc)))
	})
	return file_mup_v1_mup_proto_rawDescData
}

var file_mup_v1_mup_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mup_v1_mup_proto_goTypes = []any{
	(*Session)(nil),                // 0: mup.v1.Session
	(*SyncSnapshotRequest)(nil),    // 1: mup.v1.SyncSnapshotRequest
	(*SyncSnapshotResponse)(nil),   // 2: mup.v1.SyncSnapshotResponse
	(*StatusRequest)(nil),          // 3: mup.v1.StatusRequest
	(*StatusResponse)(nil),         // 4: mup.v1.StatusResponse
	(*ListSessionsRequest)(nil),    // 5: mup.v1.ListSessionsRequest
	(*ControlledSession)(nil),      // 6: mup.v1.ControlledSession
	(*ListSessionsResponse)(nil),   // 7: mup.v1.ListSessionsResponse
	(*SetSuppressionRequest)(nil),  // 8: mup.v1.SetSuppressionRequest
	(*SetSuppressionResponse)(nil), // 9: mup.v1.SetSuppressionResponse
	(*ReconcileResponse)(nil),      // 10: mup.v1.ReconcileResponse
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_mup_v1_mup_proto_depIdxs = []int32{
	0,  // 0: mup.v1.SyncSnapshotRequest.sessions:type_name -> mup.v1.Session
	0,  // 1: mup.v1.ControlledSession.session:type_name -> mup.v1.Session
	6,  // 2: mup.v1.ListSessionsResponse.sessions:type_name -> mup.v1.ControlledSession
	6,  // 3: mup.v1.SetSuppressionResponse.session:type_name -> mup.v1.ControlledSession
	1,  // 4: mup.v1.ObserverIngestService.SyncSnapshot:input_type -> mup.v1.SyncSnapshotRequest
	3,  // 5: mup.v1.ControllerService.Status:input_type -> mup.v1.StatusRequest
	5,  // 6: mup.v1.ControllerService.ListSessions:input_type -> mup.v1.ListSessionsRequest
	8,  // 7: mup.v1.ControllerService.SetSuppression:input_type -> mup.v1.SetSuppressionRequest
	11, // 8: mup.v1.ControllerService.Reconcile:input_type -> google.protobuf.Empty
	2,  // 9: mup.v1.ObserverIngestService.SyncSnapshot:output_type -> mup.v1.SyncSnapshotResponse
	4,  // 10: mup.v1.ControllerService.Status:output_type -> mup.v1.StatusResponse
	7,  // 11: mup.v1.ControllerService.ListSessions:output_type -> mup.v1.ListSessionsResponse
	9,  // 12: mup.v1.ControllerService.SetSuppression:output_type -> mup.v1.SetSuppressionResponse
	10, // 13: mup.v1.ControllerService.Reconcile:output_type -> mup.v1.ReconcileResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_mup_v1_mup_proto_init() }
func file_mup_v1_mup_proto_init() {
	if File_mup_v1_mup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mup_v1_mup_proto_rawDesc), len(file_mup_v1_mup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mup_v1_mup_proto_goTypes,
		DependencyIndexes: file_mup_v1_mup_proto_depIdxs,
		MessageInfos:      file_mup_v1_mup_proto_msgTypes,
	}.Build()
	File_mup_v1_mup_proto = out.File
	file_mup_v1_mup_proto_goTypes = nil
	file_mup_v1_mup_proto_depIdxs = nil
}
